In [2]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [3]:
df = pd.DataFrame(rng.randint(0, 10, (3,4)),
                 columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [5]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [6]:
np.sin(df * np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [10]:
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                'New York': 19651127, 'Florida' : 19552868,
                'Illinois': 149995}, name='population')
area = pd.Series({'Alaska': 1723337, 'California': 423967,
                   'Texas' : 695662,
                   'New York' : 141297,
                   'Florida' : 170312,
                   'Illinois' : 149995}, name='area')


In [11]:
population / area

Alaska               NaN
California     90.413926
Florida       114.806168
Illinois        1.000000
New York      139.076746
Texas          38.018740
dtype: float64

In [12]:
area.index | population.index

Index(['Alaska', 'California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [14]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [16]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [18]:
A = pd.DataFrame(rng.randint(0, 20,(2, 2)),
                columns=list('AB'))
A

A   B
0   0  11
1  11  16

In [21]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                columns=list('BAC'))
B

B  A  C
0  9  2  6
1  3  8  2
2  4  2  6

In [22]:
A + B

A     B   C
0   2.0  20.0 NaN
1  19.0  19.0 NaN
2   NaN   NaN NaN

In [23]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   2.0  20.0  15.5
1  19.0  19.0  11.5
2  11.5  13.5  15.5

In [24]:
A = rng.randint(10, size=(3, 4))
A

array([[4, 8, 6, 1],
       [3, 8, 1, 9],
       [8, 9, 4, 1]])

In [25]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1,  0, -5,  8],
       [ 4,  1, -2,  0]])

In [28]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1  0 -5  8
2  4  1 -2  0

In [29]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -4  0 -2 -7
1 -5  0 -7  1
2 -1  0 -5 -8

In [31]:
halfrow = df.iloc[0, ::2]
halfrow

Q    4
S    6
Name: 0, dtype: int32

In [32]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN -5.0 NaN
2  4.0 NaN -2.0 NaN

In [33]:
# handling missing data

import numpy as np
import pandas as pd

vals1 = np.array([1, None, 3, 4])
vals1






array([1, None, 3, 4], dtype=object)

In [36]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
154 ms ± 7.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
6.64 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [38]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [39]:
1 + np.nan

nan

In [40]:
0 * np.nan

nan

In [41]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [42]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [43]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [45]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [47]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [ ]:
#Table 3-2. Pandas handling of NAs by type 
#Typeclass Conversion when storing NAs NA sentinel value 
#floating No change np.nan object No change None or np.nan 
#integer Cast to float64 np.nan
#boolean Cast to object None or np.nan

In [ ]:
# insull() generate a boolean mask indicating missing values
#notnull() opposite to insull
# dropna() return a filterd version of data
# fillna() return a copy of the data with missing values filled or imputed


In [50]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [51]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [52]:
data.dropna()

0        1
2    hello
dtype: object

In [56]:
df = pd.DataFrame([[1,     np.nan,  2],
                  [2,        3,       5],
                 [np.nan, 4,           6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [57]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [58]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [59]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [61]:
df.dropna(axis='columns', how='all')


0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [62]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [64]:
data = pd.Series([1, np.nan,2,None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [65]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [66]:
# forward fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [67]:
# back fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [68]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [70]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0